server:
  port: 1080

spring:
  jpa:
    hibenate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: password

liquibase:
    change-log: classpath:liquibase/master.db.changelog.xml
