server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

liquibase:
    change-log: classpath:liquibase/master.db.changelog.xml
